### ISSUE TITLE
Do we "lock" the screen orientation ever?

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#100]
Even DURING a match, you can flip the tablet around and you'll change from "blue on the right" to "blue on the left".  This doesn't REALLY make sense.  Also, what do we do with all of the clicks you might have logged before this?

Now it's UNLIKELY any scouter will do this on purpose.  So we can likely rest easy.  There are two valid reason to do this:

1. the sensorListener is CONSTANTLY being called.  Locking the screen means stopping the listener.  Might mean snappier responses for context menus.  Maybe.  But clearly wasted CPU.
2. if the scouter puts the tablet on their lap, and it's slightly sloped downwards away from them, then this will register as a flip.  if the scouter doesn't notice (looking at the field) then we log incorrect data.

Currently the sensorListener is active ONLY on the Match activity page.

Some options:

1. Do nothing, let it flip, trust the scouters outright.
2. Lock it in place when they hit "start match"  (hey scouter, choose the orientation at the start and we're good to go!)
3. Lock it in place when we go to Teleop (hey scouter, in case you didn't notice it's flipped, we'll give you until teleop to fix it.  any data errors in auto we'll just live with)
4. Lock it in place when they pick their first event. (hey scouter, once you start logging events, it's locked so all event data is using the same orientation)

Looking for thoughts on this!  I think #2 makes the most sense, but we have options!

**Comment by EllaNorby** [comment]
#2 makes sense to me. We could also have a button that pops up that says "are you sure" and they have to click yes before the screen flips.

**Comment by Jeff-Stammler** [comment]
Do you mean the confirmation would pop up during a match if they flipped the screen?  I would like to avoid interrupting the scouter from watching the match with a dialog pop-up.  does that make sense?

#2 means we don't need a pop-up.  anyone else?

**Comment by Jeff-Stammler** [comment]
This is fixed in my branch now.
