### ISSUE TITLE
Stretched image coordinates in Tableau.

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#103]
Since we are stretching the field image in the app, when we try to report on the data in Tableau some of the points are going to be off the screen. So, we need to account for/fix this in Tableau Prep.

**Comment by Jeff-Stammler** [comment]
I was thinking about this, and we need to try it in Tableau.  When we loaded the field image in Tableau, didn't we tell it the max x and y sizes?  We have the fake data, so it was like 90 x 40, but I think if we use the stretched x and y values, it MIGHT be fine?  we'll have to try and see first before we worry about it.

**Comment by AdrielStammler** [comment]
Maybe. 
Either Tableau would stretch the field image or it would have some extra space. What you’re suggesting would only work if it stretches it and even if it does do it that way, I don’t think it’s a great solution.

**Comment by Jeff-Stammler** [comment]
I'm fixing up the Tableau Prep flows now and will be able to test this soon.

**Comment by Jeff-Stammler** [comment]
This works as expected in Tableau.  If we feel the field (in Tableau) is stretched and hard to look at (I didn't think so, but i didn't stare at it long) then we can add "scaling" into prep so that Tableau doesn't stretch to fit the data.  I'll close this for now and we can reopen later if needed.
