### ISSUE TITLE
How to label starting positions

### ISSUE THREAD

**Issue by EllaNorby** [AdrielStammler/CPR-Scouting-App#105]
Should the starting positions be labeled S1, S2, S3, S4 like our autos are labeled and driveteam uses or do we want them to be labeled things like amp side, subwoofer base, source side that are more self explanatory?

**Comment by Jeff-Stammler** [comment]
I'll leave this up to you all to decide.  Would could put (s1) in parentheses at the end of the description to get both.

I would favor whatever makes most sense to the people scouting.

**Comment by Jeff-Stammler** [comment]
General consensus at the Thursday meeting (9/12) was to omit (s1) and use a descriptive text for the starting positions.
Some concerns of revealing out auto's if someone sees, and just in general making it easier for the scouter.
