### ISSUE TITLE
App Update

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#118]
Currently when we want to put a new version of the app on a tablet, we have to delete the old one and install the new version. It would be much better if we could instead just install/download an update for the app.

**Comment by Jeff-Stammler** [comment]
If we published on Google Play, there's an API to handle this:
https://stackoverflow.com/questions/55939853/how-to-work-with-androids-in-app-update-api

For simple updates, i think we just need:
https://stackoverflow.com/questions/33887278/how-to-update-app

I'll test this and see if we can install the update without needing to re-install.

**Comment by Jeff-Stammler** [comment]
Just need to increment the versionCode in "build.gradle.kts (Module :app)".
when you install the new .apk, Android asks "Do you want to update this app?".
Works as expected!

**Comment by Jeff-Stammler** [comment]
Closing
