### ISSUE TITLE
Post-Match: Trap outcome needs white background

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#129]
To match the others, as well as cpr_bkgnd text color, bigger font and down arror for sure.

**Comment by EllaNorby** [comment]
Are you sure the text should be the cpr_bkgnd color? The other EditText, TextViews, and multiselect dropdown menus use black font color, I feel like making the spinner text colors would be more cohesive.

**Comment by Jeff-Stammler** [comment]
It looks black, but it's the cpr_bkgnd color.

The idea is that all inputs have a white background and cpr_bkgnd color as the text, which is the same color as the page background.  This way, the text "appears" to be transparent (like a hole, showing the page background through).
________________________________

**Comment by Jeff-Stammler** [comment]
the context menus on Match page might be black.  But there's no real background there.  They could be cpr_bkgnd color as well.  The blue is so dark it looks black anyways.

**Comment by Jeff-Stammler** [comment]
fixed in my branch.
