### ISSUE TITLE
Auto Start Note Coordinates

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#137]
Should we have the coordinates of the Auto Start Note event be 0, 0 or their start location based on what they selected? If we do, should we calculate that in the app or in Tableau Prep?

**Comment by Jeff-Stammler** [comment]
0,0 is fine.  We can figure it out in Tableau Prep.
________________________________
From: Adriel ***@***.***>
Sent: Monday, September 9, 2024 9:06 PM
To: AdrielStammler/CPR-Scouting-App ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdrielStammler/CPR-Scouting-App] Auto Start Note Coordinates (Issue #137)


Should we have the coordinates of the Auto Start Note event be 0, 0 or their start location based on what they selected? If we do, should we calculate that in the app or in Tableau Prep?

**Comment by AdrielStammler** [comment]
Ok
