### ISSUE TITLE
Pre-Match: default StartingPos if "Did They Play" is false

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#151]
Currently, we default "did they play" to true, but the default starting positions is "did not play". this doesn't make sense.

We can have a "Choose one..." perhaps as the default?  Also need to add this into the check that all fields were supplied.  This should be considered "not filled in" if chosen.

Also, if "did they play?" is unchecked, we should default the starting position to "did not play" as well.
And if unchecked, default back to "choose one...".

**Comment by AdrielStammler** [comment]
I am going to edit the options, make sure you picked one, and set it to Didn't play if you didn't play.
