### ISSUE TITLE
Logging Auto Events times accuratly.

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#182]
Because we now have a buffer in between Auto and Teleop, should we add <Buffer Length> to the time of any Auto events or subtract it form Teleop eventsɁ̦ so that the recorded times are seamless and the two phases line up nicely.

**Comment by Jeff-Stammler** [comment]
When we start teleporting we reset start time to be. Current time - 15seconds.  So that should absorb the 3sec delay.

Are you seeing anything different?

**Comment by AdrielStammler** [comment]
Oh, I didn't think about that, since we reset the start time the Auto events will just automatically be offset compared to the teleop events.
