### ISSUE TITLE
Flip screen locking

### ISSUE THREAD

**Issue by EllaNorby** [AdrielStammler/CPR-Scouting-App#218]
When you hit the back arrow and then go back to the start match page the field of play stays locked and doesn't flip.

**Comment by Jeff-Stammler** [comment]
It's calling the code correctly.  Just the setImageDrawable does do anything after hitting BACK.
I even wrapped it in a handler for RunOnUIThread to no avail.
Some days i really don't like Android.  :)
We could put up a warning when they hit "back" saying "Orientation will be locked.  Continue?" and give them a chance to cancel and fix the orientation first.
OR someone can try to research and figure it out.

**Comment by Jeff-Stammler** [comment]
with android:launchMode="singleInstance" on the activities, the flipping (and locking) WORK!
