### ISSUE TITLE
Context menu contrast

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#225]
### Context menu options blend in
The context menu's colors _(not white)_ can blend into the black background. This is especially the case with the dark red.

**Comment by Jeff-Stammler** [comment]
It's really hard to change the context menu background.  Likely need a custom pop-up item.  however, i increased the font size, brightened the colors for green/red, slightly darkened the spinner background.

**Comment by AdrielStammler** [comment]
I didn’t want you to change the back ground I just meant lighten the reds and other dark colors
