### ISSUE TITLE
Display the team in match

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#236]
Above the last event, show:
Team: 3663 - CPR Robotics
(Or whatever team...)

Need to trunk the team name to N chars (whatever fits) so we don't wrap and mess up layout.  Or if we can make the layout not wrap and have Java just trunk it for us that's better yet.

**Comment by EllaNorby** [comment]
Also add the team name to the pre match page that just shows the field

**Comment by Jeff-Stammler** [comment]
@EllaNorby this is already there.  When you pick (or when one is pre-picked) the team name is there beside it.  do you mean something else?

**Comment by EllaNorby** [comment]
@Jeff Stammler If you hit the next button on the pre match page but haven't hit start match yet.

**Comment by Jeff-Stammler** [comment]
@EllaNorby got it.  That's what this bug is for.  The entire Match page should always show the team.  Thanks for clarifying!
