### ISSUE TITLE
Cant pass an auto picked up note.

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#267]
It currently doesn't let you select pass if the note you have was picked up in auto. This is because it is looking at the next events for an auto pickup which doesn't include a pass.

We could just put pass in the options because you could go to the center and just pass all of them.

**Comment by Jeff-Stammler** [comment]
Easy to fix.  Just never thought anyone would do it!  :)

**Comment by Jeff-Stammler** [comment]
Added it into CPR-EventData.xlsx file
