### ISSUE TITLE
Crashes in practice mode

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#268]
When in practice mode and you say go to next match after practicing a match it crashes. Not a big deal you didn't have any data anyway.

**Comment by AdrielStammler** [comment]
maybe its just my device because I tested and it crashed the same way in non practice mode.

**Comment by EllaNorby** [comment]
It doesn't crash on my laptop

**Comment by AdrielStammler** [comment]
Ok that’s what I thought might be the case.
