### ISSUE TITLE
Resets

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#271]
If they for any reason decide to reset the match, we just miss the match unless they need to pause for a short period. So we need a reset or start over button during both auto and teleop. It would clear all the data and either bring you back to before the match is started or the prematch page.

**Comment by EllaNorby** [comment]
Could we add this to the Post match page? If the match is ended early because of a field fault, they can click to end the match early and there can be a checkbox they can press to reset/clear all the data from that match.

**Comment by Jeff-Stammler** [comment]
That makes sense - I like it.  Like a red text checkbox for "Field Fault - Reset Match", and the SUBMIT button turns into "RESET".

This works only after we change the logging to be all cached, and write out to the files only when they hit "Submit".
