### ISSUE TITLE
Do we want to get to submit page early?

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#64]
What if we want to re-transmit (QR code, BT, other?) match results?  Should be have a way to quickly get to the Submit page from the Pre-Match page?

**Comment by AdrielStammler** [comment]
Yes, I think we do because if you accidentally hit done or the data doesn't go through you don't want to force the scouter to go through a match just to get back to that page. At the moment you are forced to only go in a loop through the pages.

**Comment by Jeff-Stammler** [comment]
Team decided "YES" on 9/3/2024 meeting.
