### ISSUE TITLE
What are the four integers in Globals for?

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#80]
The four integers:
    public static int CurrentCompetitionId;
    public static int CurrentMatchNumber;
    public static int CurrentTeamNumber;
    public static int CurrentDeviceId;
I'm pretty sure we don't use these so should they be gotten rid of?

**Comment by Jeff-Stammler** [comment]
These should be set in Pre-Match (possibly okay to do when changing event to Match).  Should be the current values (DeviceId might need to be read from SharedPreferences).  This will be used by the Logger.

**Comment by Jeff-Stammler** [comment]
We didn't use Team Number, but we did need "ScoutingTeam".  That's been modified and now that we have a logger, they're used.  Close this question if that answers it for you.

**Comment by AdrielStammler** [comment]
Ok, I was just confused cause it says we aren't using them and we have the Shared Preferences so I wasn't sure if it was left over code that should've been gotten rid of.
