### ISSUE TITLE
Need to log the spinner choice correctly

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#87]
Right now we're logging spinner.toString() which gives:
androidx.appcompat.widget.AppCompatSpinner{37f2ea4 VFED..CL. ........ 566,20-807,67 #7f080247 app:id/spinner_StartingPosition aid=1073741828}
(not helpful).

Need to fix all spinners.

**Comment by AdrielStammler** [comment]
Should this be closed. Because you linked a pull request?
