### ISSUE TITLE
How should we log transitional events in between the game phases?

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#89]
Currently we aren't capturing or doing anything about getting the Auto ended with a note and Teleop started with a note. Do we tell the logger, and it logs this? Or do we add it in prep, because we know when it occurs and where in the events it goes?

**Comment by Jeff-Stammler** [comment]
We could do it in Tableau, but the one icky problem we'll have is the list of options you have after you pickup an auto_note are different than after picking up a teleop_note.  (slightly - but it could be more severe in future years).

IMHO, it would be better to log the end of auto (with a note) and log a start of teleop (pickup).

**Comment by AdrielStammler** [comment]
I think we don't need to it. If we want to find out number of times you ended with a note in auto all you do is look at previous events that are in auto and the actual event is in teleop.

**Comment by AdrielStammler** [comment]
It is also much easier to not. And as I said it is easy to handle in Tableau, and if we want in Tableau Prep, we can add in those two events if auto ended with a note.
