### ISSUE TITLE
Do we need to track if we started with a note?

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#90]
Not only in Pre-Match (layout change to ask, variables, but also LOG a time-based event at 0 time?  (what do we use for X,Y?) so that the first option a scouter has are the "score/miss" ones.

**Comment by Jeff-Stammler** [comment]
Team: We need to ask and log a zero-time event (so we don't have orphaned events), but do we need to record whether they did or not?  Did we ever use that information for reporting this past season?

I'm going to guess not.  Either way, we can have a calculated column looking for pickup events at time=0 to see.

**Comment by AdrielStammler** [comment]
I am going to just add it as a check box in Pre-Match and then when you start the match it logs an event at the location of the start pos at the time 0.

**Comment by Jeff-Stammler** [comment]
Keep "Need to resubmit data" as the last checkbox.

**Comment by AdrielStammler** [comment]
Ok
