### ISSUE TITLE
The Dropdowns use the TextView instead of the EditText.

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#97]
Currently the Drop down is set to appear on the click of the label for the dropdown and the items selected are also displayed on the label rather than the edit text.

**Comment by EllaNorby** [comment]
I'm confused....
My code had the dropdowns use a textview, so what are you wanting to change

**Comment by AdrielStammler** [comment]
Each one has a Textview and an EditText:
TextView:   Comments: 
EditText:     enter here

**Comment by EllaNorby** [comment]
I think you're looking at Mr. Stammler's stand in code, I've been using TextViews andnote EditText
![Screenshot 2024-09-05 185337](https://github.com/user-attachments/assets/1e0b2c0c-b85f-4115-9c3b-a9e09dda9758)

**Comment by AdrielStammler** [comment]
Ok well it was the first one
